init -5 python:
    #These all are the same right now. Find a way to make the addition of each buffer unique
    #One idea is to create a solution class. This class would have an attribute that represents what
    #
    #Furthermore, I need to also consider that some of these introduce impurities as well. 
    
    def requires_sample(func):
        """
        Another creation by claude. I actually had no idea that this is what those decorator things looked like in
        implementation. I definately think that the best way to try using AI tools is to have it as a refactoring and 
        debugging assistant.
        """
        def wrapper(*args, **kwargs):
            if curr_sample is None:
                renpy.notify("Select a sample first.")
                return
            return func(*args, **kwargs)
        return wrapper
    
    
    """
    The code below was generated by claude. The key advantage it has over my implementation is that by utilizing higher order functions it 
    centralizes the logic that controls the act of adding a solvent making it easier to introduce new solvents. If I want to extend this to
    other lab procedures, then this design is far better.
    
    @requires_sample
    def add_solvent(solvent):
        value = int('0' + renpy.input(default='0', allow=['1','2','3','4','5','6','7','8','9','0'], length=4, prompt="How many microliters would you like to add?"))
        if not curr_sample.has_space(value):
            return "Not enough space in your tube!"
        curr_sample.add_solvent(value, solvent)
        return None

    def make_solvent_action(key):
        def action():
            message = renpy.invoke_in_new_context(add_solvent, SOLVENTS[key])
            if message:
                renpy.notify(message)   # runs back in the screen's own context
        return action
    
    
    Im going to frankenstein the two approaches together so that I can have the broad application of the add_solvent (that I have built much of my code around)
    with the unique individual behaviour.
    use_ethanol   = make_solvent_action("ethanol")
    use_bufferAE  = make_solvent_action("bufferAE")
    use_PBS       = make_solvent_action("PBS")
    use_proteaseK = make_solvent_action("proteaseK")
    use_bufferAL  = make_solvent_action("bufferAL")
    use_bufferAW1 = make_solvent_action("bufferAW1")
    use_bufferAW2 = make_solvent_action("bufferAW2")
    The Functions below have been replaced by the implementation above.
    """

#For now we will not worry about specific amounts added but if the thing is done at all. 
    @requires_sample
    def use_ethanol():
        #Ethanol is entirely solvent and should not introduce any impurities (I think)
        if add_solvent(400):
            curr_sample.has_ethanol = True
    
    @requires_sample
    def use_bufferAE():
        if curr_sample.proteins_washed and not curr_sample.has_chaotropic_salts and add_solvent(150):
            #Washes all DNA that is bound to spin column into tube. Not fully realistic but good enough. 
            curr_sample.has_AE = True
        else:
            renpy.notify("You do not need buffer ATE at this stage!")

    @requires_sample    
    def use_PBS():
        pass

    @requires_sample
    def use_proteaseK():
        if curr_sample._decay_rate == 0:
            renpy.notify("There are no more DNAses that need digesting!")
        if add_solvent(20):
            curr_sample.add_proteaseK()

    @requires_sample
    def use_bufferAL():
        if curr_sample._mass_DNA == 0:
            renpy.notify("You have lysed all cells within this tube!")
        if add_solvent(400):
            curr_sample.free_DNA(1)

    @requires_sample
    def use_bufferAW1():
        #Washes protein impurities off DNA but also introduces new impurity in chaotropic salts
        if not curr_sample._mass_DNA_bound == 0 and add_solvent(500):
            curr_sample.has_AW1 = True
        else:
            renpy.notify("There is no DNA to wash proteins off of!")

    @requires_sample
    def use_bufferAW2():
        if curr_sample.has_chaotropic_salts and add_solvent(500):
            curr_sample.has_AW2 = True
        else:
            renpy.notify("There are no chaotropic salts to wash off the DNA!")

    @requires_sample
    def add_solvent(value):
        #value = int(renpy.input(default='0', allow=['1','2','3','4','5','6','7','8','9','0'], length=4, prompt="How many microliters would you like to add?"))

        if not curr_sample.has_space(value):
            if curr_sample.has_spin_column:
                renpy.notify("If you add any more solvent the spin column will overflow")
                return False
            else: 
                renpy.notify("Not enough space in your tube!")
                return False
        else:
            if curr_sample.get_total_volume() != 0:
                curr_sample.uniformly_mixed = False

            curr_sample.add_solvent(value)

            return True
        
    def use_2mlTube():
        global total_tubes
        total_tubes += 1
        num_tubes = total_tubes
        new_tube_name = renpy.invoke_in_new_context(renpy.input, default=f'Sample Tube {num_tubes}', length=20, prompt="Label your tube")

        evidence.add_to_inventory(Instance_Item(new_tube_name, image_name="balance_tube_idle", usable=True, action=use_sample, instance=Tube_2ml(new_tube_name)))
        curr_sample = evidence.get_item(new_tube_name).instance

    @requires_sample
    def use_spinColumn():
        if curr_sample.has_spin_column:
            renpy.notify("You already have a spin column in this tube!")
        elif curr_sample.get_total_volume() != 0:
            renpy.notify("There is already solution in this tube.")
        else:
            curr_sample.add_spin_column()
    
    def use_sample():
        global curr_sample
        curr_sample = evidence.get_item(last_used_item).instance
    
    @requires_sample
    def use_incubater():
        if curr_sample._decay_rate == 0:
            renpy.notify("You have already incubated this sample and there is nothing left for the enzymes to digest!")
        else:
            curr_sample.incubate()
    
    @requires_sample
    def use_centrifuge():
        #if curr_sample is None:  (Replaced by decorator)
        #renpy.notify("Select a sample first.")
        #return
        print(curr_sample.label)

        if not curr_sample.has_spin_column:
            renpy.notify("You do not need to centrifuge. If you want to homogenize the mixture use the mini centrifuge and vortex machine!")
        elif curr_sample.centrifuged:
            renpy.notify("You have already centrifuged this tube.")
        else:

            if curr_sample.has_AW1:
                curr_sample.proteins_washed = True
                curr_sample.has_chaotropic_salts = True
                
                #During centrifuging a minor amount of DNA will be washed off (I Think) 
                curr_sample.free_bound_DNA(0.05)

            elif curr_sample.has_AW2:
                curr_sample.has_chaotropic_salts = False
                
                #During centrifuging a minor amount of DNA will be washed off (I Think) 
                curr_sample.free_bound_DNA(0.05)
            
            elif curr_sample.has_AE:
                #Bit of a simplification as not 100% of DNA attached to spin column will be washed off but it is good enough for this game.ws
                curr_sample.free_bound_DNA(1)
            
            
            else:
                #Centrifuging to adhere DNA to the column
                bound_percentage = check_binding(curr_sample)

                curr_sample._mass_DNA_bound += curr_sample._mass_DNA_free * bound_percentage
                curr_sample._mass_DNA_free -= curr_sample._mass_DNA_free * bound_percentage
            
            #Centrifuge seperates layers of liquid (if I remember correctly)
            curr_sample.uniformly_mixed = False
            curr_sample.centrifuged = True
            renpy.play("placeholder_centrifuge.mp3")
    

    @requires_sample
    def use_vortex_and_mini_centrifuge():
        curr_sample.uniformly_mixed = True
        
    
    def focus_evidence_inventory():
        """
        Switches the inventory to the evidence tab and makes sure it's on
        screen, so the player has something to pick a destination tube from.
        """
        global selected_inventory
        selected_inventory = evidence
        if not renpy.get_screen("inventory"):
            renpy.show_screen("inventory")
            renpy.hide_screen("open_inv")


    def start_transfer():
        """
        Asks the player whether they want to move the tube's liquid contents
        or its physical spin column, then focuses the evidence inventory so
        they can pick a destination tube.
        """
        global transfer_source, transfer_mode

        if curr_sample is None:
            renpy.notify("Select a sample first.")
            return

        mode = renpy.invoke_in_new_context(renpy.call_screen, "choose_transfer_type")

        if mode is "cancel":
            cancel_transfer()
        elif mode == "spin_column" and not curr_sample.has_spin_column:
            renpy.notify(f"{curr_sample.label} doesn't have a spin column to transfer.")
            return
        else:
            transfer_source = curr_sample
            transfer_mode = mode
            focus_evidence_inventory()
            renpy.notify(
                "Select a tube to transfer the spin column into."
                if mode == "spin_column" else
                "Select a tube to transfer the solution into."
            )
 

    def cancel_transfer():
        global transfer_source, transfer_mode
        transfer_source = None
        transfer_mode = None
        renpy.notify("Transfer cancelled.")


    def attempt_transfer(item):
        global transfer_source, transfer_mode

        destination = getattr(item, "instance", None)

        if not isinstance(destination, Tube_2ml):
            renpy.notify("You can only transfer into a sample tube.")
            return

        if destination is transfer_source:
            renpy.notify("Choose a different tube to transfer into.")
            return

        if transfer_mode == "spin_column":
            transfer_spin_column(transfer_source, destination)
        else:
            transfer_solution(transfer_source, destination)

        transfer_source = None
        transfer_mode = None


    def check_binding(source):
        value = 0.1

        #Checks if there is even distribution for uniform reaction with silica
        if source.uniformly_mixed:
            value += 0.28

        if source.has_ethanol:
            value += 0.28
        
        if source.get_total_volume() <= 1350:
            value += 0.28

        return value


    def transfer_solution(source, destination):
        """
        Moves the liquid contents of source into destination. If destination
        has a spin column, the bound fraction (per check_binding) sticks to
        the column as _mass_DNA_bound rather than staying free in solution;
        the rest passes through as flow-through, same as before.
        """
        if source.has_spin_column:
            renpy.notify("You need to do something about the spin column first!")
            return

        #This is an incredibly inelegant hardcode but you never really transfer more than half a tube of sample
        transfer_volume = min(700, source.get_total_volume())

        if not destination.has_space(transfer_volume):
            renpy.notify(f"{destination.label} doesn't have enough space for that transfer!")
            return


        destination.uniformly_mixed = source.uniformly_mixed
        destination.has_AE = source.has_AE
        destination.has_AW1 = source.has_AW1
        destination.has_AW2 = source.has_AW2
        destination.has_ethanol = source.has_ethanol

        #If there are still active DNAses you will also expose the contents of the new tube to them
        destination._decay_rate = source._decay_rate


        #What percent of the source volume is transferred?
        #TODO If time permits find a way to punish not transferring uniform solution by uneven DNA distribution (Probably wont have time for this :)
        percentage_transferred = transfer_volume / source.get_total_volume()
        
        #DNA still trapped in cells and solvent will not adhere to spin column and transfer the same always
        #Additionally, I am accutely aware there may be some floating point BS going on here but I think it should be fine.
        destination._mass_DNA += source._mass_DNA * percentage_transferred
        destination._volume_solvent += source._volume_solvent  * percentage_transferred

        source._mass_DNA -= source._mass_DNA * percentage_transferred
        source._volume_solvent -= source._volume_solvent  * percentage_transferred

        #Free DNA will always be transferred as it is in the solution regardless of the presence of spin column.
        destination._mass_DNA_free += source._mass_DNA_free * percentage_transferred 
        source._mass_DNA_free -= source._mass_DNA_free * percentage_transferred


        #Update concentrations to accurately reflect what has gone on
        destination.calculate_concentration_DNA()
        source.calculate_concentration_DNA()

        renpy.notify(f"Transferred solution from {source.label} to {destination.label}.")


    def transfer_spin_column(source, destination):
        """
        Moves the physical spin column - and whatever DNA is currently bound
        to it - out of source and into destination, leaving both tubes'
        liquid contents untouched. Mirrors pulling the column out of the
        collection tube and dropping it into a fresh one.
        """
        if destination.has_spin_column:
            renpy.notify(f"{destination.label} already has a spin column in it.")
            return
        elif destination.get_total_volume() > 0:
            renpy.notify("There is already solution in this tube.")
            return

        destination.has_spin_column = True
        destination._mass_DNA_bound = source._mass_DNA_bound

        source.has_spin_column = False
        source._mass_DNA_bound = 0

        destination.has_chaotropic_salts = source.has_chaotropic_salts
        destination.proteins_washed = source.proteins_washed

        renpy.notify(f"Moved the spin column from {source.label} to {destination.label}.")
    

    DECAY_TICK_SECONDS = 1.0

    def degrade_all_samples():
        """
        Called on a repeating timer to age every sample tube currently in
        the evidence inventory, regardless of which one is selected.
        """
        for item in evidence._inventory:
            instance = getattr(item, "instance", None)
            if isinstance(instance, Tube_2ml):
                instance.degrade(DECAY_TICK_SECONDS)
    
    
screen choose_transfer_type():
    modal True
    zorder 100
    add Solid("#0008")

    frame:
        align (0.5, 0.5)
        vbox:
            spacing 15
            text "What would you like to transfer?"
            textbutton "Solution" action Confirm("This will transfer solution to the selected tube. Proceed?", Return("solution"))
            textbutton "Spin Column" action Return("spin_column")
            textbutton "Neither" action Return("cancel")


screen choose_discard_type():
    modal True
    zorder 100
    add Solid("#0008")

    frame:
        align (0.5, 0.5)
        vbox:
            spacing 15
            text "What would you like to discard?"
            textbutton "Tube" action Confirm("Are you certain you want to discard the tube and all its contents?", Function(discard_sample, curr_sample))
            textbutton "Spin Column" action Confirm("Are you certain you wany to discard the spin column and everything attached to it?", Function(discard_spin_column, curr_sample))
            textbutton "Neither" action Hide("choose_discard_type")


 
